import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CustomCursorManager from './components/CustomCursor/contexts/manager'
import CustomCursor from './components/CustomCursor/CustomCursor'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#eeebe6]">
        <CustomCursorManager>
          <div className="page-wrapper">
            <CustomCursor />
            {children}
          </div>
        </CustomCursorManager>
      </body>
    </html>
  )
}
